### PR TITLE
Beta Release Features

### PR DESCRIPTION
**Pull request by warrn**

### CODE REVIEW

**Comment by warrn** [comment]
It looks ok right now, metadata and delete functionality are added, tagging will be added next... dunno about pagination...

**Comment by warrn** [comment]
Gonna take a nap

**Comment by warrn** [comment]
Also @kochman you should get this version of the server up, I don't think I'll be doing any more backend changes before the beta release

**Comment by kochman** [comment]
Looking great. Only thing is I'm setting Content Security Policy headers on poly.rpi.edu that break some of the included scripts, so I'm fixing that now.

Also, if you have any time to fix the MockDB in the tests, then we can merge this to master too.

**Comment by warrn** [comment]
Okay added more "bugfixes", this is the version I think is gonna be shown

**Comment by kochman** [comment]
Deployed

**Comment by warrn** [comment]
Actually deleted now functions correctly. I fixed that with the latest changes

**Comment by warrn** [comment]
Testing is fixed, waiting on approval

**Comment by JCBird1012** [comment]
This LGTM.

**Pull request merged**
